const ActionTypes = {
  //wishlist
  CREATE_WISHLIST: 'wishlist/CREATE_WISHLIST',
  DELETE_WISHLIST: 'wishlist/DELETE_WISHLIST',
  CLEAR_WISHLIST: 'wishlist/CLEAR_WISHLIST',
  LOAD_DATA_WISHLIST: 'wishlist/LOAD_DATA_WISHLIST',
  LOAD_DATA_PAGE_WISHLIST: 'wishlist/LOAD_DATA_PAGE_WISHLIST',
  REMOVE_WISHLIST: 'wishlist/REMOVE_WISHLIST',

  // fetching
  START_FETCHING: 'fetching/START_FETCHING',
  FETCH_SUCCESS: 'fetching/FETCH_SUCCESS',
  FETCH_PAGER_SUCCESS: 'fetching/FETCH_PAGER_SUCCESS',
  CREATE_SUCCESS: 'fetching/CREATE_SUCCESS',
  UPDATE_SUCCESS: 'fetching/UPDATE_SUCCESS',
  DELETE_SUCCESS: 'fetching/DELETE_SUCCESS',
  CLEAR_SUCCESS: 'fetching/CLEAR_SUCCESS',
  STOP_FETCHING: 'fetching/STOP_FETCHING',
  FETCH_LOAD_MORE_DATA_SUCCESS: 'fetching/FETCH_LOAD_MORE_DATA_SUCCESS',
  START_FETCHING_AUTH: 'fetching/START_FETCHING_AUTH',
  STOP_FETCHING_AUTH: 'fetching/STOP_FETCHING_AUTH',
  START_FETCHING_PAYMENT: 'fetching/START_FETCHING_PAYMENT',
  STOP_FETCHING_PAYMENT: 'fetching/STOP_FETCHING_PAYMENT',
  START_FETCHING_HTML_BLOCK: 'fetching/START_FETCHING_HTML_BLOCK',
  STOP_FETCHING_HTML_BLOCK: 'fetching/STOP_FETCHING_HTML_BLOCK',
  START_FETCHING_LOCATION_GG: 'fetching/START_FETCHING_LOCATION_GG',
  STOP_FETCHING_LOCATION_GG: 'fetching/STOP_FETCHING_LOCATION_GG',
  START_FETCHING_WISHLIST: 'fetching/START_FETCHING_WISHLIST',
  STOP_FETCHING_WISHLIST: 'fetching/STOP_FETCHING_WISHLIST',
  START_FETCHING_REVIEW: 'fetching/START_FETCHING_REVIEW',
  STOP_FETCHING_REVIEW: 'fetching/STOP_FETCHING_REVIEW',
  FETCH_ERROR: 'fetching/FETCH_ERROR',

  // notification
  SHOW_NOTIFICATION: 'notification/SHOW_NOTIFICATION',
  RESET_NOTIFICATION: 'notification/RESET_NOTIFICATION',

  // alert
  SHOW_ALERT: 'alert/SHOW_ALERT',
  HIDE_ALERT: 'alert/HIDE_ALERT',

  // loading
  LOADING_START: 'loading/LOADING_START',
  LOADING_END: 'loading/LOADING_END',

  // user
  USER_LOGGING_IN: 'user/USER_LOGGING_IN',
  USER_LOGGED_IN: 'user/USER_LOGGED_IN',
  USER_LOGGED_OUT: 'user/USER_LOGGED_OUT',
  USER_REGISTERED: 'user/USER_REGISTERED',
  USER_AUTH_ERROR: 'user/USER_AUTH_ERROR',
  USER_VERIFIED: 'user/USER_VERIFIED',
  AUTHENTICATE: 'user/AUTHENTICATE',
  USER_EMAIL_VERIFIED: 'user/USER_EMAIL_VERIFIED',
  USER_PHONE_REGISTER: 'user/USER_PHONE_REGISTER',
  USER_SKIP_PHONE_REGISTER: 'user/USER_SKIP_PHONE_REGISTER',
  USER_SKIP_LOCATION_REGISTER: 'user/USER_SKIP_LOCATION_REGISTER',
  USER_SKIP_SINGPASS: 'user/USER_SKIP_SINGPASS',
  USER_PHONE_VERIFIED: 'user/USER_PHONE_VERIFIED',
  MODAL_VERIFY_BY_PHONE: 'user/MODAL_VERIFY_BY_PHONE',
  USER_LOCATION: 'user/USER_LOCATION',
  USER_LOCATION_ID: 'user/USER_LOCATION_ID',
  USER_INFO: 'user/USER_INFO',
  USER_INFO_FACEBOOK: 'user/USER_INFO_FACEBOOK',
  USER_INFO_MODAL: 'user/USER_INFO_MODAL',
  USER_UPDATE: 'user/USER_UPDATE',
  SET_AUTH: 'user/SET_AUTH',
  USER_UPDATE_INFO: 'user/USER_UPDATE_INFO',
  SET_USER: 'user/SET_USER',
  SET_AUTH_VERIFY_PHONE: 'user/SET_AUTH_VERIFY_PHONE',
  USER_PHONE_PROFILE: 'user/USER_PHONE_PROFILE',
  USER_VERIFIED_PHONE_PROFILE: 'user/USER_VERIFIED_PHONE_PROFILE',
  SET_DEFAULT_VERIFIED_PHONE_PROFILE: 'user/SET_DEFAULT_VERIFIED_PHONE_PROFILE',
  USER_SET_PLAY_ID: 'user/USER_SET_PLAY_ID',
  USER_TERM: 'user/USER_TERM',
  START_FETCHING_USER_VERIFYING: 'user/START_FETCHING_USER_VERIFYING',
  STOP_FETCHING_USER_VERIFYING: 'user/STOP_FETCHING_USER_VERIFYING',
  START_SEND_PASSWORD_CODE: 'user/START_SEND_PASSWORD_CODE',
  STOP_SEND_PASSWORD_CODE: 'user/STOP_SEND_PASSWORD_CODE',
  SET_STATE_VERIFYING_PHONE: 'user/SET_STATE_VERIFYING_PHONE',
  GET_BLOCKED_USER: 'user/GET_BLOCKED_USER',
  BLOCK_USER: 'user/BLOCK_USER',
  UNBLOCK_USER: 'user/UNBLOCK_USER',
  REFRESH_TOKEN: 'user/REFRESH_TOKEN',
  USER_RESET_PHONE: 'user/USER_RESET_PHONE',
  // SingPass
  IS_VERIFYING_SINGPASS: 'user/IS_VERIFYING_SINGPASS',
  SET_USER_SINGPASS: 'user/SET_USER_SINGPASS',
  CLEAR_USER_SINGPASS: 'user/CLEAR_USER_SINGPASS',

  // subscription
  SUBSCRIBE_START: 'subscribe/LOAD_START',
  SUBSCRIPBE_SUCCESS: 'subscribe/LOAD_SUCCESS',
  UNSUBSCRIBE_SUCCESS: 'unsubscribe/LOAD_SUCCESS',
  SUBSCRIBE_ERROR: 'subscribe/LOAD_ERROR',

  SUBSCRIBE_QUEUE_SUCCESS: 'subscribe/SUBSCRIBE_QUEUE_SUCCESS',

  //order
  GET_ORDER: `order/GET_ORDER`,
  SET_ORDER: `order/SET_ORDER`,
  SET_CHANGE_ORDER: `order/SET_CHANGE_ORDER`,
  SET_DUPLICATE_ORDER: `order/SET_DUPLICATE_ORDER`,
  ORDER_CLEAR_SUCCESS: `order/ORDER_CLEAR_SUCCESS`,
  ORDER_PROMO_CODE: `order/ORDER_PROMO_CODE`,
  UPDATE_ORDER_SUCCESS: 'order/UPDATE_ORDER_SUCCESS',
  SET_CURRENT_DATE: 'order/SET_CURRENT_DATE',
  RESET_CALENDAR: 'order/RESET_CALENDAR',
  UPDATE_REVIEW_USER_SUCCESS: 'order/UPDATE_REVIEW_USER_SUCCESS',
  //  config
  CONFIG_SUCCESS: 'config/LOAD_CONFIG_SUCCESS',
  CONFIG_PAGER_SUCCESS: 'config/LOAD_CONFIG_PAGER_SUCCESS',
  CONFIG_CLEAR: 'config/CLEAR_SUCCESS',
  CONFIG_UPDATE: 'config/UPDATE_CONFIG_SUCCESS',

  CLEAR_ROOM_SUCCESS: 'chat/CLEAR_ROOM_SUCCESS',
  FETCH_ROOM_SUCCESS: 'chat/FETCH_ROOM_SUCCESS',
  FETCH_ROOM_ERROR: 'chat/FETCH_ROOM_ERROR',
  REGISTER_ROOM: 'chat/REGISTER_ROOM',
  FETCH_MESSAGE_SUCCESS: 'chat/FETCH_MESSAGE_SUCCESS',
  FETCH_MESSAGE_ERROR: 'chat/FETCH_MESSAGE_ERROR',
  FETCH_SENT_MESSAGE_SUCCESS: 'chat/FETCH_SENT_MESSAGE_SUCCESS',
  FETCH_ACTIVE_GROUP_CHAT_KEY: 'chat/FETCH_ACTIVE_GROUP_CHAT_KEY',
  FETCH_BLOCKED_GROUP_CHAT: 'chat/FETCH_BLOCKED_GROUP_CHAT',
  FETCH_LIST_USER_INFO: 'chat/FETCH_LIST_USER_INFO',
  // nav bar
  LOAD_DATA_CATEGORY: 'nav/LOAD_DATA_CATEGORY',
  // categories
  LOAD_PRODUCTS_CATEGORY: 'categories/LOAD_PRODUCTS_CATEGORY',
  LOAD_TOTAL_PRODUCTS: 'categories/LOAD_TOTAL_PRODUCTS',
  SET_ACTIVE_ITEM: 'products/SET_ACTIVE_ITEM',
  // payment
  CREATE_PAYMENT_SUCCESS: 'payment/CREATE_PAYMENT_SUCCESS',
  LOAD_DATA_PAYMENT_DETAILS: 'payment/LOAD_DATA_PAYMENT_DETAILS',
  UPDATE_PAYMENT_SUCCESS: 'payment/UPDATE_PAYMENT_SUCCESS',
  RESET_PAYMENT_INFO: 'payment/RESET_PAYMENT_INFO',
  CHECK_PAYMENT_ID: 'payment/CHECK_PAYMENT_ID',
  CHARGE_PAYMENT_SUCCESS: 'payment/CHARGE_PAYMENT_SUCCESS',
  DELIVERY_INFO: 'payment/DELIVERY_INFO',
  // form
  FETCH_FORM_FIELD_ERROR_SUCCESS: 'form/FETCH_FORM_FIELD_ERROR_SUCCESS',
  FETCH_RESET_FORM_FIELD_ERROR_SUCCESS:
    'form/FETCH_RESET_FORM_FIELD_ERROR_SUCCESS',

  // html
  FETCH_HTML_BLOCK_SUCCESS: 'html/FETCH_HTML_BLOCK_SUCCESS',

  // location
  FETCH_LOCATION_GOOGLE_SUCCESS: 'location/FETCH_LOCATION_GOOGLE_SUCCESS',
  FETCH_LOCATION_GOOGLE_ERROR: 'location/FETCH_LOCATION_GOOGLE_ERROR',
  // html
  FETCH_USE_NOTIFICATION_SUCCESS: 'html/FETCH_USE_NOTIFICATION_SUCCESS',

  // Reactour
  FETCH_OPEN_TOUR: 'tour/FETCH_OPEN_TOUR',
  FETCH_CLOSE_TOUR: 'tour/FETCH_CLOSE_TOUR',
  FETCH_TOGGLE_DROPDOWN_PROFILE: 'tour/FETCH_TOGGLE_DROPDOWN_PROFILE',
  FETCH_TOGGLE_DROPDOWN_CALENDAR: 'tour/FETCH_TOGGLE_DROPDOWN_CALENDAR',

  // REVIEW
  FETCHING_LOADING_USER_REVIEW: 'review/FETCHING_LOADING_USER_REVIEW',
  FETCHING_COUNT_USER_REVIEW: 'review/FETCHING_COUNT_USER_REVIEW',
  CLEAR_FETCHING_USER_REVIEW: 'review/CLEAR_FETCHING_USER_REVIEW',

  //update cache
  USER_ACTION_DELETE_PRODUCT: 'userAction/USER_ACTION_DELETE_PRODUCT',
  USER_ACTION_CREATE_PRODUCT: 'userAction/USER_ACTION_DELETE_PRODUCT',
  USER_ACTION_UPDATE_NOTIFICATION: 'userAction/USER_ACTION_UPDATE_NOTIFICATION',
  REMOVE_USER_ACTION: 'userAction/REMOVE_USER_ACTION',

  // Location
  REMOVE_ERROR_LOCATION_GG: 'location/REMOVE_ERROR_LOCATION_GG'
}

export default ActionTypes
