export default {
  UNKNOWN: 'UNKNOWN',

  REVIEW_EXIST: 'REVIEW_EXIST',

  USER_EXIST: 'USER_EXIST',

  EMAIL_EXIST: 'EMAIL_EXIST',

  PHONE_NUMBER_EXIST: 'PHONE_NUMBER_EXIST',

  PROMO_CODE_EXIST: 'PROMO_CODE_EXIST',

  CODE_EXIST: 'CODE_EXIST',

  WISHLIST_EXISTS: 'WISHLIST_EXISTS',

  MEMBERSHIP_EXISTS: 'MEMBERSHIP_EXISTS',

  NAME_EXISTS: 'NAME_EXISTS',

  SLUG_EXISTS: 'SLUG_EXISTS',

  MISSED_FIELD: 'MISSED_FIELD',

  MISSED_FIELD2: 'MISSED_FIELD2',

  USER_PASSWORD_NOT_MATCH: 'USER_PASSWORD_NOT_MATCH',

  USER_CURRENT_PASSWORD_NOT_MATCH: 'USER_CURRENT_PASSWORD_NOT_MATCH',

  USER_CODE_NOT_MATCH: 'USER_CODE_NOT_MATCH',

  INVALID_EMAIL_ADDRESS: 'INVALID_EMAIL_ADDRESS',

  INVALID_NAME: 'INVALID_NAME',

  INVALID_RATING: 'INVALID_RATING',

  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',

  INVALID_PRICE: 'INVALID_PRICE',

  INVALID_PROMO_CODE: 'INVALID_PROMO_CODE',

  INVALID_CATEGORY: 'INVALID_CATEGORY',

  INVALID_VALIDATE_SMS: 'INVALID_VALIDATE_SMS',

  ERROR_SEND_SMS: 'ERROR_SEND_SMS',

  UNAUTHORIZED: 'UNAUTHORIZED',

  ACCESS_DENIED: 'ACCESS_DENIED',

  ORDER_NOT_CONFIRMED: 'ORDER_NOT_CONFIRMED',

  NOT_FOUND: 'NOT_FOUND',

  USER_NOT_FOUND: 'USER_NOT_FOUND',

  LENDOR_NOT_FOUND: 'LENDOR_NOT_FOUND',

  LENDEE_NOT_FOUND: 'LENDEE_NOT_FOUND',

  PROMO_CODE_NOT_FOUND: 'PROMO_CODE_NOT_FOUND',

  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',

  DATE_EXPIRED: 'DATE_EXPIRED',

  ORDER_ALREADY_CANCELED: 'ORDER_ALREADY_CANCELED',

  PRODUCT_INVALID_DAY: 'PRODUCT_INVALID_DAY',

  ORDER_ALREADY_ACCEPTED: 'ORDER_ALREADY_ACCEPTED',

  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  DUPLICATE_LOAN_DURATION_ORDER: 'DUPLICATE_LOAN_DURATION_ORDER'
}